# Generated by Django 6.0.2 on 2026-02-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefa",
            name="create",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="deadline",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="finished",
            field=models.DateField(null=True),
        ),
    ]
