# Generated by Django 6.0.2 on 2026-02-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0002_alter_tarefa_create_alter_tarefa_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
    ]
